import { createAction } from '@reduxjs/toolkit';
import {
  ISetSystemIsLoadedBoards,
  ISetSystemIsLoadedColumns,
  ISetSystemIsLoadedTodos,
  ISetSystemActiveTodoId,
  ISetSystemEditCommentId,
  ISetSystemEditableBoardId,
  ISetSystemEditableColumnId,
  ISetSystemEditableHeadingId,
  ISetSystemEditableCardId,
  ISetSystemEditableSubCardId,
  ISetSystemActivePopupId,
  ISetSystemLanguage,
  ISetSystemIsSearchMode,
  ISetSystemReplyCommentId,
  ISetSystemIsOpenProfile,
  ISetSystemActiveBoardId,
  ISetSystemActiveBoardReadableId,
  ISetSystemActiveTodoReadableId,
  ISetSystemDroppedFiles,
  ISetGalleryImagesInfo,
  ISetIsOpenFormattingHelp, ISetSystemActiveSubTodoReadableId, ISetSystemActiveSubTodoId,
} from '@type/actions';

export const SystemActions = {
  effect: {
    setLanguage: createAction<ISetSystemLanguage>('SYSTEM-EFFECT/SET_LANGUAGE'),
    fetchLanguage: createAction('SYSTEM-EFFECT/FETCH_LANGUAGE'),
    setEditableCardIdByColumnId: createAction<number>('SYSTEM/SET_EDITABLE_CARD_ID_BY_COLUMN_ID'),
  },
  setLanguage: createAction<ISetSystemLanguage>('SYSTEM/SET_LANGUAGE'),
  setIsLoadedBoards: createAction<ISetSystemIsLoadedBoards>('SYSTEM/SET_IS_LOADED_BOARDS'),
  setIsLoadedColumns: createAction<ISetSystemIsLoadedColumns>('SYSTEM/SET_IS_LOADED_COLUMNS'),
  setIsLoadedTodos: createAction<ISetSystemIsLoadedTodos>('SYSTEM/SET_IS_LOADED_TODOS'),
  setActivePopupId: createAction<ISetSystemActivePopupId>('SYSTEM/SET_ACTIVE_POPUP_ID'),
  setEditableBoardId: createAction<ISetSystemEditableBoardId>('SYSTEM/SET_EDITABLE_BOARD_ID'),
  setEditableColumnId: createAction<ISetSystemEditableColumnId>('SYSTEM/SET_EDITABLE_COLUMN_ID'),
  setEditableHeadingId: createAction<ISetSystemEditableHeadingId>('SYSTEM/SET_EDITABLE_HEADING_ID'),
  setEditableCardId: createAction<ISetSystemEditableCardId>('SYSTEM/SET_EDITABLE_CARD_ID'),
  setEditableSubCardId: createAction<ISetSystemEditableSubCardId>('SYSTEM/SET_EDITABLE_SUB_CARD_ID'),
  setIsSearchMode: createAction<ISetSystemIsSearchMode>('SYSTEM/SET_IS_SEARCH_MODE'),
  setActiveTodoId: createAction<ISetSystemActiveTodoId>('SYSTEM/SET_ACTIVE_TODO_ID'),
  setActiveSubTodoId: createAction<ISetSystemActiveSubTodoId>('SYSTEM/SET_ACTIVE_SUB_TODO_ID'),
  setEditCommentId: createAction<ISetSystemEditCommentId>('SYSTEM/SET_EDIT_COMMENT_ID'),
  setReplyCommentId: createAction<ISetSystemReplyCommentId>('SYSTEM/SET_REPLY_COMMENT_ID'),
  setIsOpenProfile: createAction<ISetSystemIsOpenProfile>('SYSTEM/SET_IS_OPEN_PROFILE'),
  setActiveBoardId: createAction<ISetSystemActiveBoardId>('SYSTEM/SET_ACTIVE_BOARD_ID'),
  setActiveBoardReadableId: createAction<ISetSystemActiveBoardReadableId>('SYSTEM/SET_ACTIVE_BOARD_READABLE_ID'),
  setActiveTodoReadableId: createAction<ISetSystemActiveTodoReadableId>('SYSTEM/SET_ACTIVE_TODO_READABLE_ID'),
  setActiveSubTodoReadableId: createAction<ISetSystemActiveSubTodoReadableId>('SYSTEM/SET_ACTIVE_SUB_TODO_READABLE_ID'),
  setDroppedFiles: createAction<ISetSystemDroppedFiles>('SYSTEM/SET_DROPPED_FILES'),
  setGalleryImagesInfo: createAction<ISetGalleryImagesInfo>('SYSTEM/SET_GALLERY_IMAGES_INFO'),
  setIsOpenFormattingHelp: createAction<ISetIsOpenFormattingHelp>('SYSTEM/SET_IS_OPEN_FORMATTING_HELP'),
};
