export const TYPES = {
  HttpClient: Symbol.for('HttpClient'),
  WSClient: Symbol.for('WSClient'),
  Services: Symbol.for('Services'),
  AuthService: Symbol.for('AuthService'),
  UserService: Symbol.for('UserService'),
  BoardService: Symbol.for('BoardService'),
  ColumnService: Symbol.for('ColumnService'),
  HeadingService: Symbol.for('HeadingService'),
  TodoService: Symbol.for('TodoService'),
  CommentService: Symbol.for('CommentService'),
  CommentAttachmentService: Symbol.for('CommentAttachmentService'),
  SearchService: Symbol.for('SearchService'),
  UpdateService: Symbol.for('UpdateService'),
};
